### ISSUE TITLE
Issue with _retrieved_at on resource edit

### ISSUE THREAD

**Issue by francescomalatesta** [orchidsoftware/crud#13]
Hi,

I am trying the crud package, it's really cool. However, I have an issue while editing a resource. I tried with a blank Laravel project User model. When saving my updates, I get the following error:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column '_retrieved_at' in 'field list' (SQL: update `users` set `_retrieved_at` = 2021-01-11T13:18:32.000000Z, `users`.`updated_at` = 2021-01-11 13:20:05 where `id` = 1)
```

The issue seems to be the parameter in the EditScreen commandBar in "src/Screens/EditScreen.php". Is there something I have to disable I don't know about?

Thanks a lot!

**Comment by rabol** [comment]
I have the same on an newly created resource

**Comment by tabuna** [comment]
Hotfix with the [release 2.5.1](https://github.com/orchidsoftware/crud/releases/tag/2.5.1)

**Comment by francescomalatesta** [comment]
Lovely! Thx
