### ISSUE TITLE
How to avoid the resource showing up in the sidebar

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/crud#14]
Hi

How is it possible to avoid that a resource shows up in the sidebar ?

**Comment by tabuna** [comment]
Released a new version https://github.com/orchidsoftware/crud/releases/tag/2.5.0
Which contains a method for excluding a resource from the navigation.

```php
/**
 * Get the resource should be displayed in the navigation
 *
 * @return bool
 */
public static function displayInNavigation(): bool
{
    return false;
}
```
