### ISSUE TITLE
Edit pages

### ISSUE THREAD

**Issue by jouniikaheimo** [orchidsoftware/crud#2]
Hi any change edit page split two columns? example left col-md-9 and right col-md-3?

**Comment by tabuna** [comment]
Hey @jouniikaheimo . This is an elementary package. No layouts can be changed. You can try using field concatenation:

```php
use Orchid\Screen\Fields\Group;
use Orchid\Screen\Fields\Input;

Group::make([
    Input::make('first_name'),
    Input::make('last_name'),
]);
```

Also, to improve the appearance, you can use horizontal margins:

```php
Input::make('first_name')->horizontal(),
```

If you need more, consider using Orchid only, it gives more options.
