### ISSUE TITLE
Resource 'screens' does not have the 'description' property

### ISSUE THREAD

**Issue by rabol** [orchidsoftware/crud#21]
On a Screen, there is the name and description property that is displayed as a header.
When using a CRUD / Resource there is no possibility to set the description of the Screen.

The name property of the Screen is taken from the resource::label() in the constructor

**Comment by tabuna** [comment]
Hi, what pages do you think the description should be on? Only on the list or everywhere?

**Comment by rabol** [comment]
I think it should be available on all screens / operations. maybe a resouce::description() that would be used the same way as the resource::label() in the constructor

**Comment by tabuna** [comment]
Hey, @rabol  I have added a new method:

```php
/**
 * Get the descriptions for the screen.
 *
 * @return null|string
 */
public static function description(): ?string
{
    return null;
}
```

Then it will look like this:

![image](https://user-images.githubusercontent.com/5102591/104815009-171fed00-5823-11eb-922d-bbed6d834adc.png)
