### ISSUE TITLE
Resources nav grouping issue

### ISSUE THREAD

**Issue by wsdnathan** [orchidsoftware/crud#28]
If displayInNavigation() is set to return false and would otherwise be the first Resource to be displayed in the admin sidebar nav, the ->title('Resources") type grouping never happens so all the Resources get grouped in with whatever grouping came before it.

There is another issue where Resources will have a random sort order in the nav depending on when they were added. Different servers can result in different sort orders. I suggest that the Resources sort order in nav defaults to alphabetical.

**Comment by tabuna** [comment]
We are now sorting the menu items for crud by natural order. Feel free to reopen the issue if relevant.
