### ISSUE TITLE
Any method add commandBar custom button

### ISSUE THREAD

**Issue by jouniikaheimo** [orchidsoftware/crud#3]
Hi i try to find in Orchid\Crud\Resource.php how i can add custom button in commandBar?

**Comment by mucan54** [comment]
You can  check [this line] (https://github.com/orchidsoftware/crud/blob/efe8f93a3422d46614d650a1617b75b2dd95fb5f/src/Screens/CreateScreen.php#L34) you can add any button in commandbar method.

**Comment by jouniikaheimo** [comment]
@mucan54  Yes i know i can add any button in screen... but how i can add custom button in crud resource file... 
i test if i add commandBar() function in created resource file that not working...

**Comment by tabuna** [comment]
Hey @jouniikaheimo, this is not yet available for CRUD, I am working on it

**Comment by jouniikaheimo** [comment]
Hey @tabuna i don't know if this is a good idea, but would it be how hard to do an override the same way a model is set example:

    public static $editScreen = EditScreen::class;
    public static $listScreen = listScreen::class;
    public static $createScreen = createScreen::class;

if not set use automatic default screen this make lot off new feature what can use in screen but fast make crud ??

**Comment by tabuna** [comment]
This is available through actions: https://github.com/orchidsoftware/crud#actions
