### ISSUE TITLE
Filter causes ID to display wrongly

### ISSUE THREAD

**Issue by bilogic** [orchidsoftware/crud#32]
![image](https://user-images.githubusercontent.com/946010/111947448-78608700-8b18-11eb-9dc0-bc5a624b3873.png)

1. I have 2 tables `contacts` and `payments`, related by `payments.contact_id`
2. I wrote a `QueryFilter.php` for `payments` filtering by using `contacts` information
```PHP
    public function run(Builder $builder): Builder
    {
        $searchTerm = $this->request->get('search');

        return $builder
            ->join('contacts', 'contacts.id', '=', 'payments.contact_id')
            ->where('contacts.surname', 'LIKE', '%' . $searchTerm . '%')
            ->orWhere('contacts.email', 'LIKE', '%' . $searchTerm . '%')
        ;
    }
```
3. In my `Payments.php` resource, I had to do this:
```PHP
    public function columns(): array
    {
        return [
            TD::make('id'),
        ...
    }

    public function filters(): array
    {
        return [
            \App\Orchid\Filters\PaymentsFilter::class,
            new DefaultSorted('payments.id', 'desc'),
        ];
    }
```
4. Before filter is applied, both `payments.id` and `contacts.id` shows the correct values
5. After filter is applied, `payments.id` shows the value of `contacts.id`
6. Looks like a bug to me, any idea?

Thank you.

**Comment by tabuna** [comment]
Hi, I am using links, and I have no such problem. 
Maybe join is affecting. It would be great to see the result of what is returned in its purest form.

Try to write those in the same way as I do:

```php
return $builder->whereHas('contacts', function (Builder $query) {
    $searchTerm = $this->request->get('search');

    $query
        ->where('surname', 'LIKE', '%' . $searchTerm . '%')
        ->orWhere('email', 'LIKE', '%' . $searchTerm . '%');
});
```

**Comment by bilogic** [comment]
Yes, thank you! Yours worked! Strange, what did I do wrong?

**Comment by bilogic** [comment]
@tabuna sorry to sidetrack a bit, is there a way to apply `QueryFilter.php` to a column instead of the table?
