### ISSUE TITLE
Query Builder for model

### ISSUE THREAD

**Issue by faizfizy** [orchidsoftware/crud#37]
Is there any way I can use Query Builder on the model to only retrieve selected rows? 

Or maybe this can also be achieved using Policy view() method.

**Comment by tabuna** [comment]
Hi, to modify the displayed values and use the builder use filters: 

- https://github.com/orchidsoftware/crud#defining-filters
- https://orchid.software/en/docs/filters/#eloquent-filter

**Comment by faizfizy** [comment]
> Hi, to modify the displayed values and use the builder use filters:
> 
> * https://github.com/orchidsoftware/crud#defining-filters
> * https://orchid.software/en/docs/filters/#eloquent-filter

Oops, somehow I missed this. Thanks!
