### ISSUE TITLE
Resource::rules() parameter injection

### ISSUE THREAD

**Issue by pqr** [orchidsoftware/crud#4]
According to documentation rules method accepts `$model`
<img width="859" alt="image" src="https://user-images.githubusercontent.com/451007/102981980-db8f4d00-451a-11eb-9b0c-64ae433f25df.png">

but `rules()` definition does not:
https://github.com/orchidsoftware/crud/blob/master/src/Resource.php#L225

As a result I get an error when trying to define a `rules()` method with `$model` parameter:
```
ErrorException
Declaration of App\Orchid\Resources\LocationResource::rules($model): array should be compatible with Orchid\Crud\Resource::rules(): array 
```

**Comment by tabuna** [comment]
Hey @pqr! I updated this. This should work now:

```php
public function rules(Model $model): array
{
    return [
        'slug' => [
            'required',
            Rule::unique(self::$model, 'slug')->ignore($model),
        ],
    ];
}
```


https://user-images.githubusercontent.com/5102591/103000702-9714a900-453c-11eb-95cf-b0c9b103f047.mp4

**Comment by pqr** [comment]
Confirm, works now!
