### ISSUE TITLE
Use Listener with Resource

### ISSUE THREAD

**Issue by kirtangajjar** [orchidsoftware/crud#46]
I have created a Resource class, but I need to use a [listener](https://orchid.software/en/docs/listener/). 

So how do I use a listener with a Resource class?

**Comment by kirtangajjar** [comment]
cc @tabuna

**Comment by tabuna** [comment]
Hi @kirtangajjar, If you need a listener, then you have already grown out of the CRUD package and need to use full-fledged screens.
