### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by bilogic** [orchidsoftware/crud#49]
Hi,

I added the following to `phpunit.xml`
```XML
        <server name="DB_CONNECTION" value="sqlite"/>
        <server name="DB_DATABASE" value=":memory:"/>
```

But I still get the errors when running tests
```BASH
Action (Orchid\Crud\Tests\Action)
 ✘ Run action with empty resource  1034 ms
   ┐
   ├ Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 no such table: posts (SQL: insert into "posts" ("title", "description", "body", "updated_at", "created_at") values (Oh dear!., By the time at the mushroom for a good deal until she had tired herself out with trying, the poor., So she called softly after it, never once considering how in the window, I only knew how to speak again. The rabbit-hole went straight on like a serpent. She had already heard her sentence three of the treat. When the procession moved on, three of her ever getting out of a muchness"--did you ever eat a little bird as soon as she could, and soon found herself safe in a moment to think to herself, as usual. I wonder what was coming. It was all very well as she could. 'The game's going on rather., 2021-07-06 07:24:15, 2021-07-06 07:24:15))
```

I guess the tables were not created. Personally, I always have these 2 lines in my tests
```PHP
    use \Illuminate\Foundation\Testing\DatabaseMigrations;
    use \Illuminate\Foundation\Testing\RefreshDatabase;
```

Any idea why the tables are not created? Thank you.

**Comment by tabuna** [comment]
Hi, you don't need to add anything to pass the tests. You can watch the public [GitHub Actions](https://github.com/orchidsoftware/crud/blob/92f9736d715be852c79e00ab3f1e50447bd9ec02/.github/workflows/run-tests.yml#L1) to see the [work in action](https://github.com/orchidsoftware/crud/actions/runs/1004029123).

It should be in a few easy steps:

```bash
git clone https://github.com/orchidsoftware/crud.git
```

Then go to the directory:

```bash
cd crud
```

Install dependencies:

```bash
composer install
```

And finally run them:

```bash
./vendor/bin/phpunit
```

**Comment by mxts** [comment]
Hi

When I run on my machine, which database will the tests use? The test failure was due to missing table.

Can I have GitHub actions on my forked tepo as well?

**Comment by bilogic** [comment]
Ok your steps worked. Thank you.
