### ISSUE TITLE
Hide default actions in ListScreen

### ISSUE THREAD

**Issue by jlevers** [orchidsoftware/crud#51]
Thanks for all the great work on this project!

Is there a way to hide the default `View` and `Update` actions on each record in the list view? Currently it seems like the only real way to override anything in the `ListScreen` is to create a full custom screen.

**Comment by tabuna** [comment]
Hi, @jlevers. The CRUD build package relies on eloquent models where view or update permissions are granted by specifying a policy. To hide them, you need to create a policy for your model. For example:

```php
namespace App\Policies;

use App\Models\User;
use App\Models\Post;
use Illuminate\Auth\Access\HandlesAuthorization;

class PostPolicy
{
    use HandlesAuthorization;

    /**
     * Determine whether the user can update the post.
     *
     * @param  User  $user
     * @param  Post  $post
     * @return mixed
     */
    public function update(User $user, Post $post)
    {
        return true;
    }
}
```

You can find more information on the [package page](https://github.com/orchidsoftware/crud#policies) and on the [laravel documentation page](https://laravel.com/docs/8.x/authorization#creating-policies).

**Comment by jlevers** [comment]
Gotcha -- that makes sense. Thank you!
