### ISSUE TITLE
Delete confirmation dialog does not work

### ISSUE THREAD

**Issue by pqr** [orchidsoftware/crud#6]
<img width="900" alt="image" src="https://user-images.githubusercontent.com/451007/103013935-05fafd80-454f-11eb-8d62-21f82b21d973.png">

orchid/platform 9.14.0
orchid/crud 2.1.0

**Comment by tabuna** [comment]
A possible reason is that required fields (or rules) are not filled. And for this, the form did not react. 
I have added to the deletion and ordinance methods ignoring the form rules.

Still not working? How can I reproduce

**Comment by tabuna** [comment]
If you looked from safari, then it was solved recently here https://github.com/orchidsoftware/platform/issues/1482

**Comment by pqr** [comment]
Confirm, works now!
