### ISSUE TITLE
Resource menu item disappears when permission not granted for one resource

### ISSUE THREAD

**Issue by ap1969** [orchidsoftware/crud#61]
Hi,
First - thanks for the great software, this is saving SOOOO much time.

I've spotted an issue though: I have multiple resources defined, and if the current user has access to all resources, then the "Resources" top-level menu item appears.

But if any one of the resources is not permitted, then the top level Resource item disappears. 

See screenshots:

![without-permissions](https://user-images.githubusercontent.com/1629592/147010077-ac7b8e30-9364-4219-b1f5-386a97a63092.png)
![with-permissions](https://user-images.githubusercontent.com/1629592/147010080-3b450755-7ddb-4a15-8d71-edf75fc6d69c.png)

**Comment by tabuna** [comment]
Hi Andy. It should be fixed with the [release](https://github.com/orchidsoftware/crud/releases/tag/3.3.1).

**Comment by ap1969** [comment]
Fantastic!
