### ISSUE TITLE
Question about delete action

### ISSUE THREAD

**Issue by interpegasus** [orchidsoftware/crud#69]
I would like to know if there is a setting for disabling the delete CRUD action in a model?
Thank you

**Comment by interpegasus** [comment]
<img width="184" alt="Screen Shot 2022-05-20 at 5 47 04 PM" src="https://user-images.githubusercontent.com/934795/169621675-75da2260-25a2-4ba4-bed9-a0e1ef5053fb.png">

**Comment by tabuna** [comment]
For default actions, we focus on the policies of the model:  https://orchid.software/en/docs/packages/crud/#policies
