### ISSUE TITLE
Active menu is not highlighting on list with pagination

### ISSUE THREAD

**Issue by szonov** [orchidsoftware/crud#74]
on page `/crud/list/task-resources` resource menu item is highlighted.
on page `/crud/list/task-resources?page=2` resource menu item is NOT highlighted.

the same behaviour with any query on resource list page, for example with using filter.

**Comment by szonov** [comment]
It can be fixed in Orchid\Crud\Arbitrator@activeMenu by adding one more item:
```php
route('platform.resource.list', [
     'resource' => $resource::uriKey() . '?*'
]),
```

**Comment by tabuna** [comment]
Hi @szonov, can you do a PR?

**Comment by szonov** [comment]
Hi @tabuna. I will try

**Comment by szonov** [comment]
First try was not success. PHP Storm formatting applied
