### ISSUE TITLE
Moving to other navigation dropdown

### ISSUE THREAD

**Issue by AlizHarb** [orchidsoftware/crud#97]
Hello
i was trying to move the resource to other navigation dropdown but did not get work, will appreciate if you can help.

`Menu::make(__('Game Mechanics'))
                ->icon('bs.gamepad')
                ->list([
                    Menu::make(__('Ranks'))
                        ->icon('bs.dash')
                        ->route('platform.resource.rank')
                        ->permission('admin.games.ranks'),
                ]),`
                
` /**
    * Get the resource should be displayed in the navigation
    *
    * @return bool
    */
   public static function displayInNavigation(): bool
   {
       return false;
   }`

**Comment by tabuna** [comment]
Hi! You were almost there. The only issue in the code is the resource link. It should be, for example, like this: `route('platform.resource.list', UserResource::uriKey())`. Here’s the complete, corrected example:

```php
Menu::make(__('Game Mechanics'))
    ->icon('bs.gamepad')
    ->list([
        Menu::make(__('Ranks'))
            ->icon('bs.dash')
            ->route('platform.resource.list', YouClass::uriKey()) // Replace
            ->permission('admin.games.ranks'),
    ]);
```
