### ISSUE TITLE
Translate issue

### ISSUE THREAD

**Issue by plescanos** [orchidsoftware/crud#98]
Hi, 
The power of CRUD and platform is awesome, I really love it.
The only problem I have is translating to spanish (and other languages I think) I tried using the locale config, using the json lang file, creating lang file in vendor, I mean I tried everything , but I can 't trasnlate the module in the picture attached, do you have any idea where is this module or how can I rtanslate?
<img width="1138" alt="imagen" src="https://github.com/orchidsoftware/crud/assets/20541853/9ad80cb8-9460-4daf-a909-41ba422954b0">
<img width="650" alt="Captura de pantalla 2024-06-19 a las 8 12 02" src="https://github.com/orchidsoftware/crud/assets/20541853/affbd1d2-e74a-4787-9437-06ace461e07d">

**Comment by tabuna** [comment]
To enable localization, you'll need to adjust the `locale` setting in the `config/app.php` file.

Language translations are located at https://github.com/orchidsoftware/platform/tree/master/resources/lang. You can enhance these translations as necessary.

**Comment by plescanos** [comment]
> To enable localization, you'll need to adjust the `locale` setting in the `config/app.php` file.
> 
> Language translations are located at https://github.com/orchidsoftware/platform/tree/master/resources/lang. You can enhance these translations as necessary.

Hi, yesm is the first thign I did. Nothing happened, I jus noticed, is not crud thing, in platform screen have the same problem , in fact, I translate almost everything even making hard coding, but this particular part of platform I can't find, thanks for answer.

**Comment by plescanos** [comment]
Ok, I finally found the solution for this trasnlate issue. Using override process, copy `table.blade.php`  from `vendor\orchid\platform\src\Scree\Layouts` to `\resources\views\vendor\platform\layouts` and change lines 99 to 115 to language you need.

es.json (or other languages) do not work

Anyway, thanks for this powerful tool !!

```
    protected function textNotFound(): string
    {
        if (count(request()->query()) !== 0) {
            return __('No results found for your current filters');
        }

        return __('There are no objects currently displayed');
    }

    protected function subNotFound(): string
    {
        if (count(request()->query()) !== 0) {
            return __('Try adjusting your filter settings or removing it altogether to see more data');
        }

        return __('Import or create objects, or check back later for updates');
    }
```

**Comment by plescanos** [comment]
Anyway If you want to use the variables, I try to override file but do not work, so I harcoded the `vendor\orchid\platform\src\Screen\Layouts\Table.php` on lines 99 to 115

```
    protected function textNotFound(): string
    {
        if (count(request()->query()) !== 0) {
            return __('No results found for your current filters');
        }

        return __('There are no objects currently displayed');
    }

    protected function subNotFound(): string
    {
        if (count(request()->query()) !== 0) {
            return __('Try adjusting your filter settings or removing it altogether to see more data');
        }

        return __('Import or create objects, or check back later for updates');
    }
```
